#  define version
version: 2.1

# define orbs
orbs: 
  node: circleci/node@5.0.0

# define jobs
jobs:
  # define jp name
  build:
    docker: 
      - image: cimg/node:18.20.0
    # define steps
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: npm install
      - run: 
          name: build
          command: npm run build
      - run: 
          name: deploy
          command: npm run deploy

workflows: 
  # define name
  build-deploy:
    jobs:
      - build :
          filters: 
            branches: 
              only: development